In [7]:
import numpy as np
import pandas as pd

credits = pd.read_csv('/Users/prastutupreti/AI_prastut/datasets/tmdb_5000_credits.csv')
movies = pd.read_csv('/Users/prastutupreti/AI_prastut/datasets/tmdb_5000_movies.csv')

movies.head(3)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466

In [8]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [9]:
credits.shape

(4803, 4)

In [10]:
# merging the datasets because we have two datasets for one movie
# id and title are same

movies = movies.merge(credits, on='title')

movies.head(3)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."

In [11]:
# separating columns for recommendation
# genres
# id
# keywords
# title
# popularity
# overview
# cast
# crew

movies = movies[['id', 'genres', 'keywords', 'title', 'popularity', 'overview', 'cast', 'crew']]

movies.info()

<class 'pandas.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          4809 non-null   int64
 1   genres      4809 non-null   str
 2   keywords    4809 non-null   str
 3   title       4809 non-null   str
 4   popularity  4809 non-null   float64
 5   overview    4806 non-null   str
 6   cast        4809 non-null   str
 7   crew        4809 non-null   str
dtypes: float64(1), int64(1), str(6)
memory usage: 300.7 KB

In [12]:
movies.dropna(subset=['overview'], inplace=True)

In [13]:
import ast

In [14]:
movies['genres'] = movies['genres'].apply(
    lambda x: [i['name'] for i in ast.literal_eval(x)]
)

In [15]:
movies['keywords'] = movies['keywords'].apply(
    lambda x: [i['name'] for i in ast.literal_eval(x)]
)

In [16]:
movies['cast'] = movies['cast'].apply(
    lambda x: [i['name'] for i in ast.literal_eval(x)]
)

In [17]:
movies['cast'] = movies['cast'].apply(lambda x: x[:3])

In [18]:
movies['cast'].head()

0    [Sam Worthington, Zoe Saldana, Sigourney Weaver]
1       [Johnny Depp, Orlando Bloom, Keira Knightley]
2        [Daniel Craig, Christoph Waltz, Léa Seydoux]
3        [Christian Bale, Michael Caine, Gary Oldman]
4      [Taylor Kitsch, Lynn Collins, Samantha Morton]
Name: cast, dtype: object

In [19]:
movies['keywords'].apply(len).head()

0    21
1    16
2     7
3    21
4    16
Name: keywords, dtype: int64

In [20]:
def get_director(x):
    for i in ast.literal_eval(x):
        if i['job'] == 'Director':
            return [i['name']]
    return []

In [21]:
movies['crew'] = movies['crew'].apply(get_director)

In [22]:
movies['crew'].head(10)

0        [James Cameron]
1       [Gore Verbinski]
2           [Sam Mendes]
3    [Christopher Nolan]
4       [Andrew Stanton]
5            [Sam Raimi]
6         [Byron Howard]
7          [Joss Whedon]
8          [David Yates]
9          [Zack Snyder]
Name: crew, dtype: object

In [23]:
movies['genres'] = movies['genres'].apply(
    lambda x: [i.replace(" ", "_") for i in x]
)

movies['keywords'] = movies['keywords'].apply(
    lambda x: [i.replace(" ", "_") for i in x]
)

movies['cast'] = movies['cast'].apply(
    lambda x: [i.replace(" ", "_") for i in x]
)

movies['crew'] = movies['crew'].apply(
    lambda x: [i.replace(" ", "_") for i in x]
)

In [24]:
movies['crew'].head()

0        [James_Cameron]
1       [Gore_Verbinski]
2           [Sam_Mendes]
3    [Christopher_Nolan]
4       [Andrew_Stanton]
Name: crew, dtype: object

In [25]:
movies['tags'] = (
    movies['overview'].apply(lambda x: [x])
    + movies['genres']
    + movies['keywords']
    + movies['cast']
    + movies['crew']
)

In [26]:
movies.head()

,id,genres,keywords,title,popularity,overview,cast,crew,tags
0,19995,"[Action, Adventure, Fantasy, Science_Fiction]","[culture_clash, future, space_war, space_colon...",Avatar,150.437577,"In the 22nd century, a paraplegic Marine is di...","[Sam_Worthington, Zoe_Saldana, Sigourney_Weaver]",[James_Cameron],"[In the 22nd century, a paraplegic Marine is d..."
1,285,"[Adventure, Fantasy, Action]","[ocean, drug_abuse, exotic_island, east_india_...",Pirates of the Caribbean: At World's End,139.082615,"Captain Barbossa, long believed to be dead, ha...","[Johnny_Depp, Orlando_Bloom, Keira_Knightley]",[Gore_Verbinski],"[Captain Barbossa, long believed to be dead, h..."
2,206647,"[Action, Adventure, Crime]","[spy, based_on_novel, secret_agent, sequel, mi...",Spectre,107.376788,A cryptic message from Bond’s past sends him o...,"[Daniel_Craig, Christoph_Waltz, Léa_Seydoux]",[Sam_Mendes],[A cryptic message from Bond’s past sends him ...
3,49026,"[Action, Crime, Drama, Thriller]","[dc_comics, crime_fighter, terrorist, secret_i...",The Dark Knight Rises,112.312950,Following the death of District Attorney Harve...,"[Christian_Bale, Michael_Caine, Gary_Oldman]",[Christopher_Nolan],[Following the death of District Attorney Harv...
4,49529,"[Action, Adventure, Science_Fiction]","[based_on_novel, mars, medallion, space_travel...",John Carter,43.926995,"John Carter is a war-weary, former military ca...","[Taylor_Kitsch, Lynn_Collins, Samantha_Morton]",[Andrew_Stanton],"[John Carter is a war-weary, former military c..."

In [27]:
new_df = movies[['id', 'title', 'tags']].copy()

In [28]:
new_df['tags'] = new_df['tags'].apply(
    lambda x: " ".join(x)
)

In [29]:
new_df['tags'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy Science_Fiction culture_clash future space_war space_colony society space_travel futuristic romance space alien tribe alien_planet cgi marine soldier battle love_affair anti_war power_relations mind_and_soul 3d Sam_Worthington Zoe_Saldana Sigourney_Weaver James_Cameron'

In [30]:
new_df['tags'][1]

"Captain Barbossa, long believed to be dead, has come back to life and is headed to the edge of the Earth with Will Turner and Elizabeth Swann. But nothing is quite as it seems. Adventure Fantasy Action ocean drug_abuse exotic_island east_india_trading_company love_of_one's_life traitor shipwreck strong_woman ship alliance calypso afterlife fighter pirate swashbuckler aftercreditsstinger Johnny_Depp Orlando_Bloom Keira_Knightley Gore_Verbinski"

In [31]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(max_features=5000, stop_words='english')

In [32]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [33]:
vectors.shape

(4806, 5000)

In [34]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(4806, 5000))

In [35]:
words = cv.get_feature_names_out()

In [36]:
for word in words:
    print(word)

000
007
10
100
11
12
13
14
15
16
17
18
18th
19
1930s
1940s
1950s
1960s
1970s
1980
1980s
1985
1990s
19th
19th_century
20
200
2009
20th
24
25
30
300
3d
40
50
500
60
60s
70
_anderson
_army
_fox
_gary_gray
_jackson
_jr
_lee
_macy
_navy
_new_york_city
_night_shyamalan
_reilly
_russell
aaron
aaron_eckhart
abandoned
abducted
abigail_breslin
abilities
ability
able
aboard
abuse
abusive
academy
accept
accepted
accepts
access
accident
accidental
accidentally
accompanied
accomplish
account
accountant
accused
ace
achieve
act
acting
action
action_hero
actions
activist
activities
activity
actor
actors
actress
acts
actual
actually
adam
adam_sandler
adam_shankman
adams
adaptation
adapted
addict
addicted
addiction
adolescence
adopt
adopted
adoption
adopts
adrien_brody
adult
adultery
adulthood
adults
advantage
adventure
adventures
advertising
advice
affair
affairs
affection
affections
afghanistan
africa
african
african_american
aftercreditsstinger
afterlife
aftermath
age
age_difference
aged
agency
agenda
agent
agents
aggressive
aging
ago
agree
agrees
ahead
aid
aidan_quinn
aided
aids
ailing
air
airplane
airplane_crash
airport
aka
al
al_pacino
alabama
alan
alaska
albert
alcatraz
alcohol
alcoholic
alcoholism
alec_baldwin
alex
alex_kendrick
alfred_hitchcock
ali
alice
alien
alien_invasion
alien_life
aliens
alike
alive
allen
alliance
allied
allies
allow
allowing
allows
ally
alongside
alpha
alter
alternate
alternative
alzheimer
amanda
amanda_peet
amanda_seyfried
amateur
amazing
ambassador
ambition
ambitious
ambulance
ambush
america
american
american_abroad
american_civil_war
american_football
american_football_player
americans
amid
amidst
amnesia
amp
amsterdam
amusement
amusement_park
amy
amy_adams
amy_smart
ana
analyst
anarchic_comedy
ancient
ancient_rome
ancient_world
anderson
andie_macdowell
andrew
android
andy
andy_garcía
ang_lee
angel
angela
angela_bassett
angeles
angelina_jolie
angels
anger
angry
animal
animal_attack
animal_horror
animals
animated
animation
anna
anna_faris
anne
anne_hathaway
anne_moss
annette_bening
annie
anniversary
annual
answer
answers
ant
anthology
anthony
anthony_anderson
anthony_hopkins
anthropomorphism
anti
anti_hero
antics
antoine_fuqua
anton_yelchin
antonio_banderas
apart
apartheid
apartment
ape
apes
apocalypse
apocalyptic
apparent
apparently
appear
appears
apple
appointed
apprentice
approach
approaches
approaching
april
arab
arch
archaeologist
architect
arctic
area
aren
arena
argument
arise
aristocrat
armed
arms
army
arnold
arnold_schwarzenegger
arranged_marriage
arrest
arrested
arrival
arrive
arrives
arriving
arrogant
art
arthur
artificial_intelligence
artist
artistic
artists
arts
ashley
ashley_judd
ashton_kutcher
asia
aside
ask
asked
asking
asks
aspirations
aspiring
assassin
assassinate
assassination
assassins
assault
assigned
assignment
assistant
assumes
asteroid
astronaut
astronauts
asylum
athlete
atomic_bomb
attack
attacked
attacks
attempt
attempting
attempts
attending
attends
attention
attitude
attorney
attracted
attraction
attractive
audience
audiences
audition
august
aunt
austin
australia
australian
author
authorities
authority
autism
auto
avenge
average
avoid
awaits
awakens
award
away
awry
ax
babe
baby
bachelor
backdrop
background
backgrounds
bad
bag
bahamas
bail
balance
ball
ballet
baltimore
band
bandits
bangkok
banished
bank
bank_robber
bank_robbery
banker
bar
barely
bargained
barn
barney
barry
barry_levinson
bars
base
baseball
based
based_on_comic_book
based_on_graphic_novel
based_on_novel
based_on_play
based_on_stage_musical
based_on_true_events
based_on_true_story
based_on_tv_series
based_on_video_game
based_on_young_adult_novel
basement
basketball
batman
battle
battlefield
battles
battling
bay
beach
bear
bears
beast
beasts
beat
beating
beautiful
beautiful_woman
beauty
becky
becoming_an_adult
bed
bedroom
beer
befriends
began
begin
beginning
begins
behavior
beings
beliefs
believe
believed
believes
believing
beloved
ben
ben_affleck
ben_foster
ben_kingsley
ben_stiller
beneath
benicio_del_toro
benjamin
benjamin_bratt
bennett
bent
berlin
best
best_friend
bet
beth
betrayal
betrayed
bette_midler
better
betty
beverly
bible
big
bigger
biggest
biker
bikini
bill_hader
bill_murray
bill_nighy
bill_paxton
bill_pullman
billionaire
billy
billy_bob_thornton
billy_crudup
billy_crystal
biography
bird
birth
birthday
bisexual
bishop
bit
bite
bitter
bizarre
black
black_magic
black_people
blackmail
blade
blame
blind
bliss
block
blonde
blood
blood_splatter
bloodthirsty
bloody
blow
blue
board
boarding
boat
bob
bob_hoskins
bobby
bobby_farrelly
bodies
body
bodyguard
bold
bollywood
bomb
bombing
bond
bonds
bone
book
books
border
bored
boredom
boring
born
boss
boston
botched
bound
boundaries
bounty
bounty_hunter
box
boxer
boxing
boy
boyfriend
boys
brad_pitt
bradley_cooper
brain
brand
brave
bravery
brazil
brazilian
break
breakdown
breaking
breaks
brendan_fraser
brendan_gleeson
brent
brett_ratner
brian
brian_de_palma
bride
bridge
brief
brien
bright
brilliant
bring
bringing
brings
brink
britain
british
british_secret_service
brittany_murphy
broadway
broke
broken
broker
brooklyn
brothel
brother
brother_brother_relationship
brother_sister_relationship
brothers
brought
brown
bruce
bruce_willis
brutal
brutality
brutally
bryan_singer
buck
buddies
buddy
buddy_comedy
budget
build
building
built
bully
bullying
bumbling
bunny
burglar
buried
bus
business
businessman
bust
busy
butler
buy
cabin
caesar
cage
cairo
cal
california
called
calls
calvin
camcorder
came
camera
cameraman
cameras
cameron_diaz
camp
campaign
campbell
camping
campus
canada
canadian
cancer
candidate
candy
cannibal
capable
caper
capital
capitalism
capt
captain
captive
capture
captured
captures
car
car_accident
car_chase
car_crash
car_journey
car_race
card
care
career
carefree
cares
caretaker
carey_mulligan
caribbean
carl
carla_gugino
carmen
carol
carolina
carrie
carry
carrying
cars
cartel
carter
cartoon
cary_elwes
case
cases
casey_affleck
cash
casino
cast
castle
cat
cataclysm
catastrophe
catch
catches
cate_blanchett
catherine_deneuve
catherine_keener
catherine_zeta
catholic
catholicism
cattle
caught
cause
caused
causes
causing
cavalry
cave
cavemen
celebrate
celebrated
celebration
celebrity
cell
cell_phone
cemetery
center
centered
centers
central
centuries
century
ceo
ceremony
certain
chad
chain
chainsaw
challenge
challenged
challenges
champion
championship
chance
change
changed
changes
changing
channing_tatum
chaos
chaotic
chapter
character
characters
charge
charged
charismatic
charles
charlie
charlie_sheen
charlize_theron
charlotte
charm
charming
chase
chased
chases
chauffeur
cheating
cheerleader
chef
chemical
cher
chicago
chicken
chief
child
child_abuse
child_hero
child_prodigy
childhood
children
chilling
china
chinese
chip
chiwetel_ejiofor
chloe
chloë_grace_moretz
chloë_sevigny
chocolate
choice
choices
choose
chosen
chow_yun
chris
chris_columbus
chris_cooper
chris_evans
chris_hemsworth
chris_klein
chris_pine
chris_rock
chris_weitz
christ
christian
christian_bale
christian_slater
christianity
christina_applegate
christina_ricci
christine
christmas
christmas_party
christmas_tree
christoph_waltz
christopher
christopher_lambert
christopher_lloyd
christopher_nolan
christopher_plummer
christopher_walken
chronicle
chronicles
chuck
church
cia
ciarán_hinds
cigarette_smoking
cillian_murphy
cinema
circle
circuit
circumstances
circus
cities
citizens
city
civil
civil_war
civilization
claim
claims
claire
claire_danes
clan
clark
clash
class
class_differences
classes
classic
classmate
classmates
classroom
claude_van_damme
clay
clean
clear
clerk
client
clients
climate
climbing
clint_eastwood
clique
clive_owen
clock
clone
cloning
close
closed
closer
club
clubs
clue
clueless
clues
clutches
coach
coast
cocaine
cocky
code
cody
coffin
cohen
col
cold
cold_war
cole
colin
colin_farrell
colin_firth
collapse
collapses
colleague
colleagues
collect
collection
collector
college
collide
collins
collision
colombia
colonel
colony
color
colorado
colorful
coma
combat
combination
combined
come
comeback
comedian
comedic
comedy
comes
comet
comfort
comic
comics
coming
coming_of_age
coming_out
command
commander
commercial
commit
commitment
committed
common
communication
communist
community
companion
company
compete
competing
competition
competitive
complete
completely
complex
complicated
complications
composer
computer
computer_virus
con_man
conan
concert
conclusion
condition
conditions
confederate
confession
confidence
confident
conflict
confront
confronted
confronts
confused
congress
connected
connecticut
connection
connections
connects
connell
connie
connor
conquer
conscience
consequences
conservative
considered
conspiracy
conspire
constant
constantly
construction
consumed
contact
contain
containing
contains
contemporary
contend
contest
continue
continues
continuing
contract
control
controlled
controlling
controversial
convention
converge
convict
convicted
convince
convinced
convinces
cook
cooking
cool
cooper
cop
cope
cops
core
corner
corners
corporate
corporation
corpse
corrupt
corruption
cost
costume
couldn
count
country
country_music
countryside
county
coup
couple
couples
courage
courageous
course
court
court_case
courteney_cox
courtroom
cousin
cover
covert
cow
cowardliness
cowboy
crab
crack
craig
crash
crashes
crazy
create
created
creates
creation
creator
creature
creatures
crew
crime
crime_fighter
crimes
criminal
criminals
crisis
critical
crocodile
crook
crooked
cross
crossed
crosses
crown
cruel
cruelty
cruise
crush
crystal
cuba
cuba_gooding_jr
cult
cult_film
cultural
culture
culture_clash
cunning
cup
cure
curious
current
curse
cursed
custody
customers
cut
cyberpunk
cyborg
dad
daily
dakota_fanning
damage
dan
dan_aykroyd
dance
dancer
dancing
danger
dangerous
dangers
daniel
daniel_craig
daniel_day
daniel_radcliffe
danny
danny_boyle
danny_devito
danny_glover
dare
daring
dark
dark_comedy
darkest
darkness
date
dates
dating
daughter
daughters
dave
david
david_arquette
david_duchovny
david_fincher
david_gordon_green
david_morse
david_o
dax_shepard
day
days
dc
dc_comics
dea
dead
deadly
deaf
deal
dealer
dealers
dealing
deals
dean
death
death_of_a_friend
death_penalty
deaths
debt
debut
decade
decades
decapitation
deceased
deceit
deception
decide
decided
decides
decision
decisions
dedicated
deeds
deep
deeper
deeply
defeat
defend
defense
deliver
delivers
delusion
demand
demanding
demands
demi_moore
demon
demonic
demonic_possession
demons
denise_richards
denmark
dennis
dennis_dugan
dennis_hopper
dennis_quaid
dentist
denzel_washington
department
depressed
depression
depths
deputy
deranged
derek
derek_luke
descend
descends
desert
deserted
designed
desire
desires
desolate
despair
desperate
desperately
desperation
despite
destined
destiny
destroy
destroyed
destroying
destruction
details
detective
detectives
detention
determination
determine
determined
detroit
devastating
develop
developed
developer
developing
develops
device
devil
devious
devoted
diabolical
diagnosed
dialogue
diamond
diane
diane_keaton
diane_kruger
diane_lane
diary
dick
dictator
did
didn
die
died
diego
dies
differences
different
difficult
digging
dignity
diner
dinner
dinosaur
dinosaurs
dire
directed
direction
director
dirt
dirty
dirty_cop
disabled
disappearance
disappeared
disappears
disaster
disastrous
discover
discovered
discovering
discovers
discovery
disease
disfigurement
disgraced
disguise
dishonesty
disillusioned
disney
disorder
dispatched
distant
district
distrust
disturbed
disturbing
diva
divided
division
divorce
divorced
dna
doc
doctor
document
documentary
documents
does
doesn
dog
dogs
doing
doll
dollar
dollars
dolphin
domination
don
don_cheadle
donald_petrie
donald_sutherland
donnell
doomed
door
dorothy
double
double_life
doubt
doubts
doug
douglas
dr
dracula
drag
dragon
drama
dramatic
draw
drawing
drawn
draws
dream
dreams
drew
drew_barrymore
drifter
drink
drinking
drive
driven
driver
drives
driving
drop
drowning
drug
drug_abuse
drug_addiction
drug_dealer
drug_lord
drug_traffic
drugs
drunk
drunken
du
dual_identity
dude
duel
duke
dumped
duo
duringcreditsstinger
dustin_hoffman
dutch
duty
dwarves
dwayne_johnson
dying
dying_and_death
dylan
dynamic
dynasty
dysfunctional
dysfunctional_family
dystopia
dystopic_future
eager
earlier
early
earn
earth
earthquake
east
easy
eating
eccentric
economic
economy
ed_harris
eddie
eddie_griffin
eddie_murphy
edge
editor
education
edward
edward_burns
edward_norton
effort
efforts
egg
ego
egypt
egyptian
el
elaborate
elderly
election
elements
elias_koteas
elijah_wood
eliminate
elisabeth_shue
elite
elizabeth
elizabeth_banks
ella
ellen_burstyn
ellen_page
ellie
elliot
elusive
elves
elvis
embark
embarking
embarks
embroiled
emerge
emergency
emerges
emile_hirsch
emily
emily_blunt
emily_mortimer
emily_watson
emma
emma_stone
emma_thompson
emma_watson
emotional
emotionally
emotions
emperor
empire
employee
employees
employer
employs
encounter
encounters
end
end_of_the_world
ended
ending
endless
ends
enemies
enemy
energy
enforcement
engaged
engagement
engineer
england
english
enigmatic
enjoy
enlist
enlists
enormous
ensemble_cast
ensues
entangled
enter
enterprise
enters
entertainer
entertaining
entire
entirely
entity
environment
environmental
epic
epidemic
era
eric
eric_bana
erin
ernest
eroticism
erupts
escapade
escape
escape_from_prison
escaped
escapes
escaping
escort
especially
espionage
establishment
estate
estranged
eternal
ethan
ethan_hawke
eugene_levy
europe
european
eva
eva_mendes
evacuation
evade
evan_rachel_wood
eve
evening
event
events
eventually
everybody
everyday
evidence
evil
evolution
ewan_mcgregor
ex
exact
exactly
examines
exchange
exciting
exclusive
execution
executive
exercise
exist
existed
existence
existentialism
exists
exorcism
exotic
exotic_island
expectations
expected
expects
expedition
experience
experienced
experiences
experiencing
experiment
expert
explorers
explores
exploring
explosion
explosive
expose
exposed
exposes
extra
extramarital_affair
extraordinary
extraterrestrial
extraterrestrial_technology
extreme
extreme_violence
extremely
eye
eyes
face
faced
faces
facility
facing
fact
factions
factory
fail
failed
failing
fails
fairy
fairy_tale
faith
fake
fall
fallen
falling
falling_in_love
falls
false_identity
falsely_accused
fame
famed
families
family
family_relationships
famke_janssen
famous
fan
fang_vamp
fans
fantasies
fantastic
fantasy
fantasy_world
far
farewell
farm
farmer
farmhouse
fascinated
fashion
fast
faster
fat
fatal
fate
fateful
father
father_daughter_relationship
father_son_relationship
favorite
fbi
fbi_agent
fear
fears
fearsome
feature
features
featuring
federation
feel
feeling
feelings
feels
feet
fellow
female
female_friendship
female_nudity
female_protagonist
festival
feud
fi
fiancee
fiancé
fiancée
fiction
fictional
fictional_place
field
fields
fierce
fifth
fight
fighter
fighters
fighting
fights
figure
figures
files
filled
film
film_director
film_making
film_producer
filmed
filming
filmmaker
filmmakers
films
final
finale
finally
financial
finding
finds
fine
finish
finished
finn
fired
firm
first_time
fish
fish_out_of_water
fisherman
fishing
fistfight
fit
fix
flame
flashback
flat
fledgling
flee
fleeing
flees
flesh
flight
fling
flint
flirt
flood
florida
florist
flower
fly
flying
flying_saucer
focus
focused
focuses
foil
foley
folk
follow
followed
following
follows
food
foot
foot_chase
footage
football
forbidden
forbidden_love
force
forced
forces
forcing
ford
foreign
forest
forest_whitaker
forever
forget
forgiveness
form
formed
formidable
forms
formula
fort
fortune
fortune_teller
forward
foster
fought
found_footage
fourth
fox
framed
france
franchise
francis
francis_ford_coppola
francisco
frank
frank_coraci
frank_oz
frankenstein
frankie
fraternity
fraud
freak
fred
freddie_prinze_jr
freddy
free
freedom
freeze
french
fresh
freshman
friend
friendly
friends
friendship
frightening
frog
from_rags_to_riches
frontier
frozen
frustrated
fu
fugitive
fulfill
fully
fun
fund
funeral
funny
furious
future
futuristic
gabriel_byrne
gael_garcía_bernal
gain
galaxy
gambler
gambling
game
games
gandhi
gang
gang_war
gangs
gangster
gangster_boss
gangsters
garage
garden
garry_marshall
gary
gary_oldman
gary_sinise
gas
gas_station
gather
gave
gay
gay_relationship
gene_hackman
general
generation
generations
genetic
genetically
genetics
genius
gentle
geoffrey_rush
george
george_clooney
georgia
gerard_butler
german
germans
germany
getaway
gets
getting
ghetto
ghost
ghosts
giant
giants
gift
gifted
gig
girl
girlfriend
girlfriends
girls
given
gives
giving
gladiator
glamorous
glass
global
globe
glory
goal
god
gods
goes
going
gold
golden
golf
gone
good
good_vs_evil
gordon
gore
gorgeous
gorilla
gossip
got
gotham
gotham_city
government
governor
grace
grade
gradually
graduate
graduation
grand
grandfather
grandmother
grant
grave
great
greater
greatest
greece
greed
greedy
greek
green
greg
greg_kinnear
gregory_peck
grew
grief
grieving
griffin
grim
grisly
gritty
ground
group
group_of_friends
grow
growing
growing_up
grown
grows
gruesome
guard
guardian
guerrilla
guest
guests
guide
guilt
guilty
guitar
gun
gunfight
gunman
guns
gunslinger
guru
gus_van_sant
guy
guy_pearce
guys
gwyneth_paltrow
hacker
hair
half
hall
halle_berry
halloween
hallucination
hand
hand_to_hand_combat
handed
hands
handsome
hang
hanging
hangs
hannah
hapless
happen
happened
happening
happens
happily
happiness
happy
hara
harbor
hard
harlem
harmony
harold
harold_ramis
harrison_ford
harry
harsh
hart
harvard
harvey
harvey_keitel
hasn
hatches
hate
hatred
haunt
haunted
haunted_house
haunting
haven
having
havoc
hawaii
hayden_christensen
head
headed
heading
headquarters
heads
healing
health
hear
hearing
hears
heart
heartbreak
hearted
hearts
heath_ledger
heather
heaven
heavily
heavy
heavy_metal
heir
heiress
heist
held
helen
helen_hunt
helen_mirren
helena_bonham_carter
helicopter
hell
help
helped
helping
helps
henchmen
henry
hero
heroes
heroic
heroin
heroism
hidden
hide
hides
hiding
high
high_school
high_school_sports
high_school_student
higher
highest
highlands
highly
highway
hijack
hijacking
hilarious
hilary_duff
hilary_swank
hill
hills
himalaya
hip
hippie
hire
hired
hires
historic
historical
historical_figure
history
hit
hitchhiker
hitman
hits
ho
hockey
hold
holding
holds
hole
holiday
holly
hollywood
holmes
holy
home
home_invasion
homeland
homeless
homeless_person
homes
hometown
homicidal
homicide
homophobia
homosexuality
honey
honeymoon
hong
hong_kong
honor
hood
hoodlum
hook
hop
hope
hope_davis
hopelessly
hopes
hoping
hopper
horrible
horrific
horrifying
horror
horrors
horse
hospital
host
hostage
hostile
hostility
hot
hotel
hotel_room
hour
hours
house
housekeeper
housewife
housing
howard
huge
hugh_grant
hugh_jackman
human
human_animal_relationship
humanity
humankind
humans
humiliation
humor
hundreds
hunger
hungry
hunt
hunted
hunter
hunters
hunting
hurricane
husband
hustler
hypnosis
hyun
ian_mckellen
ice
ice_cube
iconic
idea
idealistic
identities
identity
idol
idyllic
ignoring
ii
iii
il
ill
illegal
illegal_immigration
illegal_prostitution
illness
image
imaginary
imagination
imagined
imax
immediately
immigrant
immigrants
immigration
immortal
immortality
impact
imperial
important
impossible
imprisoned
imprisonment
inadvertently
incest
incident
include
includes
including
increasingly
incredible
independence
independent
independent_film
india
indian
indian_lead
indiana
indians
individual
industry
inexplicably
infamous
infant
infected
infection
infidelity
infiltrate
influence
informant
information
inhabitants
inheritance
inherits
initially
injured
injury
injustice
inmates
inner
innocence
innocent
insane
insanity
inside
insists
insomnia
inspector
inspiration
inspired
inspires
inspiring
installment
instant
instantly
instead
institution
instructor
insurance
intelligence
intelligent
intends
intense
intent
intentions
intergalactic
international
internet
interrogation
interspecies_romance
intertwine
interview
interviews
intimate
intrigue
introduces
invaders
invading
invasion
invention
inventor
investigate
investigates
investigating
investigation
investigator
investment
invisible
invited
invites
involved
involves
involving
iowa
ira
iran
iranian
iraq
iraq_war
ireland
irish
iron
island
isn

In [37]:
pip install nltk

Requirement already satisfied: nltk in ./Movie_Recommendation/venv/lib/python3.13/site-packages (3.10.3)
Requirement already satisfied: defusedxml in ./Movie_Recommendation/venv/lib/python3.13/site-packages (from nltk) (0.7.1)
Requirement already satisfied: click in ./Movie_Recommendation/venv/lib/python3.13/site-packages (from nltk) (8.5.0)
Requirement already satisfied: joblib in ./Movie_Recommendation/venv/lib/python3.13/site-packages (from nltk) (1.6.0)
Requirement already satisfied: regex>=2021.8.3 in ./Movie_Recommendation/venv/lib/python3.13/site-packages (from nltk) (2026.9.29)
Requirement already satisfied: tqdm in ./Movie_Recommendation/venv/lib/python3.13/site-packages (from nltk) (4.70.1)
Requirement already satisfied: cloudpickle>=3.0 in ./Movie_Recommendation/venv/lib/python3.13/site-packages (from joblib->nltk) (3.1.2)
Note: you may need to restart the kernel to use updated packages.

In [38]:
from nltk.stem.porter import PorterStemmer

ps = PorterStemmer()

In [39]:
def stem_tags(tags):
    return [ps.stem(word) for word in tags.split()]

In [40]:
new_df['tags'] = new_df['tags'].apply(stem_tags)

In [41]:
new_df['tags'] = new_df['tags'].apply(
    lambda x: ' '.join(x)
)

In [42]:
new_df['tags'][0]

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi science_fict culture_clash futur space_war space_coloni societi space_travel futurist romanc space alien tribe alien_planet cgi marin soldier battl love_affair anti_war power_rel mind_and_soul 3d sam_worthington zoe_saldana sigourney_weav james_cameron'

In [43]:
from sklearn. metrics.pairwise import cosine_similarity

In [44]:
similarity = cosine_similarity(vectors)

In [45]:
similarity.shape

(4806, 4806)

In [46]:
similarity[0][1]

np.float64(0.0885807893036239)

In [2]:
def recommend(movie):

    # Remove unnecessary spaces
    movie = movie.strip()

    # Find the movie
    matches = movies[movies['title'].str.lower() == movie.lower()]

    # Check if movie exists
    if matches.empty:
        return []

    # Get movie index
    movie_index = matches.index[0]

    # Get similarity scores
    distances = similarity[movie_index]

    # Get top 5 similar movies
    movies_list = sorted(
        list(enumerate(distances)),
        reverse=True,
        key=lambda x: x[1]
    )[1:6]

    recommended_movies = []

    for i in movies_list:
        recommended_movies.append(movies.iloc[i[0]].title)

    return recommended_movies

In [48]:
recommend('Batman Begins')

The Dark Knight → 0.397
The Dark Knight Rises → 0.357
Batman → 0.34
Batman → 0.316
Batman & Robin → 0.312

In [49]:
import pickle

In [51]:
pickle.dump(new_df, open('movies.pkl', 'wb'))
pickle.dump(similarity, open('similarity.pkl', 'wb'))